name: Build
on:
  pull_request:
    branches: [main]
  workflow_call:

env:
  BART_VERSION: v0.10.0

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Spin
        uses: fermyon/actions/spin/setup@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install bart
        run: |
          curl -LOs https://github.com/fermyon/bartholomew/releases/download/${{ env.BART_VERSION }}/bart-${{ env.BART_VERSION }}-linux-amd64.tar.gz
          tar zxvf bart-${{ env.BART_VERSION }}-linux-amd64.tar.gz
          mv bart /usr/local/bin
      - name: Check Docs
        run: |
          bart check --shortcodes shortcodes content/* && bart check --shortcodes shortcodes content/**/*
      
      - name: Install npm packages
        run: |
          npm ci
          npm ci --prefix ./spin-up-hub

      - name: Build app
        run: |
          spin build

      # TODO: re-enable after figuring out how to confgure the current linting tool; or choose another.
      # By default, the current tool appears very aggressive, presenting errors for eg
      # multiple consecutive new-lines, non-conforming title capitalization, etc
      #
      # - name: Lint markdown
      #   run: |
      #     npm run lint-markdown

      - name: Run npm tests
        run: |
          npm test

      - name: Archive app artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app
          # These are all of the paths referenced in spin.toml
          path: |
            spin.toml
            modules/*.wasm
            content/**/*
            templates/*
            scripts/*
            config/*
            shortcodes/*
            static/**/*
            downloads/**/*
            spin-redirect.json
            spin-up-hub/dist/**/*
